# Generated by Django 5.2 on 2025-06-15 02:20

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0003_alter_corretor_email_alter_corretor_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='foto',
            field=stdimage.models.StdImageField(default=1, force_min_size=False, upload_to='corretores', variations={}, verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
