# Generated by Django 5.2 on 2025-07-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0004_alter_corretor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='codigoCorretor',
            field=models.CharField(help_text='Código único do corretor', max_length=10, unique=True, verbose_name='Código do Corretor'),
        ),
    ]
