# Generated by Django 5.2 on 2025-07-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0005_alter_corretor_codigocorretor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço:'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone:'),
        ),
    ]
