# Generated by Django 5.2 on 2025-05-26 23:32

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietarios', '0003_alter_proprietario_codigoproprietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigoImovel', models.CharField(default='Imovel', help_text='Código único do imóvel', max_length=10, unique=True, verbose_name='Código do Imóvel')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={}, verbose_name='Foto')),
                ('endereco', models.CharField(help_text='Endereço completo', max_length=100, verbose_name='Endereço')),
                ('proprietario', models.ManyToManyField(help_text='Selecione o proprietário do imóvel', to='proprietarios.proprietario', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
    ]
