# Generated by Django 5.2 on 2025-04-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoImovel', models.IntegerField(help_text='Código do Imóvel', unique=True, verbose_name='codigoImovel')),
                ('endereco', models.CharField(help_text='Endereço do Imóvel', max_length=70, verbose_name='endereco')),
                ('proprietario', models.CharField(help_text='Proprietário do Imóvel', max_length=70, verbose_name='proprietario')),
                ('tipoTransacao', models.CharField(help_text='Tipo da Transação', max_length=70, verbose_name='tipoTransacao')),
                ('valorVenda', models.DecimalField(decimal_places=2, help_text='Valor de Venda', max_digits=10, verbose_name='valorVenda')),
                ('valorIPTU', models.DecimalField(decimal_places=2, help_text='Valor do IPTU', max_digits=10, verbose_name='valorIPTU')),
                ('valorCondominio', models.DecimalField(decimal_places=2, help_text='Valor do Condomínio', max_digits=10, verbose_name='valorCondominio')),
                ('areaTotal', models.DecimalField(decimal_places=2, help_text='Área total do Imóvel', max_digits=10, verbose_name='areaTotal')),
                ('areaPrivativa', models.DecimalField(decimal_places=2, help_text='Área Privativa do Imóvel', max_digits=10, verbose_name='areaPrivativa')),
                ('areaUtil', models.DecimalField(decimal_places=2, help_text='Área Útil do Imóvel', max_digits=10, verbose_name='areaUtil')),
                ('numQuartos', models.IntegerField(help_text='Número de Quartos do Imóvel', verbose_name='numQuartos')),
                ('numBanheiros', models.IntegerField(help_text='Número de Banheiros do Imóvel', verbose_name='numBanheiros')),
                ('vagasGaragem', models.IntegerField(help_text='Vagas de Garagem', verbose_name='vagasGaragem')),
                ('tipoImovel', models.CharField(help_text='Tipo de Imóvel', max_length=70, verbose_name='tipoImovel')),
                ('caracteristicasImovel', models.CharField(help_text='Características do Imóvel', max_length=70, verbose_name='caracteristicasImovel')),
                ('comodidades', models.CharField(help_text='Comodidades do Imóvel', max_length=70, verbose_name='comodidadesImovel')),
                ('descricaoImovel', models.CharField(help_text='Descrição do Imóvel', max_length=70, verbose_name='descricaoImovel')),
            ],
        ),
    ]
