# Generated by Django 5.2 on 2025-05-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='areaPrivativa',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='areaTotal',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='areaUtil',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='caracteristicasImovel',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='comodidades',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='descricaoImovel',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='numBanheiros',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='numQuartos',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='proprietario',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='tipoImovel',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='tipoTransacao',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='vagasGaragem',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='valorCondominio',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='valorIPTU',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='valorVenda',
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(help_text='Endereço do Imóvel', max_length=255, verbose_name='endereco'),
        ),
    ]
