# Generated by Django 5.2 on 2025-06-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='disponivel_locacao',
            field=models.BooleanField(default=True, help_text='Indica se o imóvel está disponível para locação', verbose_name='Disponível para Locação'),
        ),
    ]
