# Generated by Django 5.2 on 2025-05-14 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0002_remove_imovel_areaprivativa_remove_imovel_areatotal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imovel',
        ),
    ]
