# Generated by Django 5.2 on 2025-06-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0002_imovel_disponivel_locacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='areaPrivativa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Área privativa do imóvel em metros quadrados', max_digits=10, null=True, verbose_name='Área Privativa (m²)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='areaTotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Área total do imóvel em metros quadrados', max_digits=10, null=True, verbose_name='Área Total (m²)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='areaUtil',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Área útil do imóvel em metros quadrados', max_digits=10, null=True, verbose_name='Área Útil (m²)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='Descrição das características do imóvel', null=True, verbose_name='Características'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='comodidades',
            field=models.TextField(blank=True, help_text='Lista de comodidades oferecidas pelo imóvel', null=True, verbose_name='Comodidades'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada do imóvel', null=True, verbose_name='Descrição Completa'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numBanheiros',
            field=models.IntegerField(blank=True, help_text='Número de banheiros no imóvel', null=True, verbose_name='Número de Banheiros'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numQuartos',
            field=models.IntegerField(blank=True, help_text='Número de quartos no imóvel', null=True, verbose_name='Número de Quartos'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipoImovel',
            field=models.CharField(blank=True, choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Terreno', 'Terreno'), ('Comercial', 'Comercial'), ('Outro', 'Outro')], help_text='Tipo do imóvel (casa, apartamento, etc.)', max_length=20, null=True, verbose_name='Tipo de Imóvel'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='vagasGaragem',
            field=models.IntegerField(blank=True, help_text='Número de vagas de garagem disponíveis', null=True, verbose_name='Vagas de Garagem'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valorCondominio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor mensal do condomínio', max_digits=10, null=True, verbose_name='Valor do Condomínio'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valorIPTU',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor anual do IPTU', max_digits=10, null=True, verbose_name='Valor IPTU'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valorVenda',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do imóvel para venda', max_digits=10, null=True, verbose_name='Valor de Venda'),
        ),
    ]
