# Generated by Django 5.2 on 2025-06-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0003_imovel_areaprivativa_imovel_areatotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='zona_valorizacao',
            field=models.BooleanField(default=False, help_text='Marque se o imóvel está em uma região de valorização especial (ex: bairro de luxo, próximo a universidades).'),
        ),
    ]
