# Generated by Django 5.2 on 2025-05-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='email',
        ),
    ]
