# Generated by Django 5.2 on 2025-06-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0004_imovel_zona_valorizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do imóvel', verbose_name='Última Atualização'),
        ),
    ]
