# Generated by Django 5.2 on 2025-06-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0005_imovel_ultima_atualizacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='ultima_atualizacao',
            new_name='last_updated',
        ),
    ]
