# Generated by Django 5.2 on 2025-05-15 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0005_remove_imovel_email'),
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proprietario', to='proprietarios.proprietario'),
        ),
    ]
