# Generated by Django 5.2 on 2025-05-15 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0006_imovel_proprietario'),
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietario', to='proprietarios.proprietario'),
        ),
    ]
