# Generated by Django 5.2 on 2025-07-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0006_rename_ultima_atualizacao_imovel_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='codigoImovel',
            field=models.CharField(help_text='Código único do imóvel', max_length=10, unique=True, verbose_name='Código do Imóvel'),
        ),
    ]
