# Generated by Django 5.2 on 2025-05-15 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_codigocliente_alter_cliente_endereco'),
        ('imovel', '0007_alter_imovel_proprietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='imovel',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='cliente.cliente'),
        ),
    ]
