# Generated by Django 5.2 on 2025-07-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0007_alter_imovel_codigoimovel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='endereco',
        ),
        migrations.AddField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(blank=True, help_text='Bairro onde o imóvel está localizado', max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cep',
            field=models.CharField(blank=True, help_text='Código Postal do imóvel', max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(blank=True, help_text='Cidade onde o imóvel está localizado', max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, help_text='Complemento do endereço (ex: apartamento, bloco)', max_length=50, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado onde o imóvel está localizado', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero',
            field=models.CharField(blank=True, help_text='Número do imóvel no endereço', max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='rua',
            field=models.CharField(blank=True, help_text='Nome da rua do imóvel', max_length=100, null=True, verbose_name='Rua'),
        ),
    ]
