# Generated by Django 5.2 on 2025-05-15 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0008_remove_imovel_proprietario_imovel_cliente'),
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='cliente',
        ),
        migrations.AddField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietario_imovel', to='proprietarios.proprietario'),
        ),
    ]
