# Generated by Django 5.2 on 2025-07-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0008_remove_imovel_endereco_imovel_bairro_imovel_cep_and_more'),
        ('proprietarios', '0006_alter_proprietario_codigoproprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='areaPrivativa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Privativa (m²)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='areaTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Total (m²)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='areaUtil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Útil (m²)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True, verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='comodidades',
            field=models.TextField(blank=True, null=True, verbose_name='Comodidades'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Completa'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='disponivel_locacao',
            field=models.BooleanField(default=True, verbose_name='Disponível para Locação'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='numBanheiros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Banheiros'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='numQuartos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Quartos'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='proprietario',
            field=models.ManyToManyField(to='proprietarios.proprietario', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipoImovel',
            field=models.CharField(blank=True, choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Terreno', 'Terreno'), ('Comercial', 'Comercial'), ('Outro', 'Outro')], max_length=20, null=True, verbose_name='Tipo de Imóvel'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vagasGaragem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vagas de Garagem'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valorCondominio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Condomínio'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valorIPTU',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor IPTU'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valorVenda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Venda'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='zona_valorizacao',
            field=models.BooleanField(default=False, help_text='Marque se o imóvel está em uma região de valorização especial (ex: bairro de luxo, próximo a universidades).', verbose_name='Zona de Valorização'),
        ),
    ]
