# Generated by Django 5.2 on 2025-04-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(help_text='Endereço completo', max_length=100, verbose_name='Endereço'),
        ),
    ]
