# Generated by Django 5.2 on 2025-05-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigoCliente',
            field=models.CharField(default=2, help_text='Código único do cliente', max_length=10, unique=True, verbose_name='Código do Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
