# Generated by Django 5.2 on 2025-04-27 23:55

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='visita',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={}, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='endereco',
            field=models.CharField(help_text='Endereço completo', max_length=100, verbose_name='Endereço'),
        ),
    ]
