# Generated by Django 5.2 on 2025-05-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='codigoVisita',
            field=models.CharField(default='Visita', help_text='Código único da visita', max_length=10, unique=True, verbose_name='Código da Visita'),
        ),
    ]
