# Generated by Django 5.2 on 2025-06-15 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0002_visita_codigovisita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'permissions': (('fechar_agendamento', 'Permite fazer o fechamento de uma visita'),), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
