# Generated by Django 5.2 on 2025-07-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0003_alter_visita_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='codigoVisita',
            field=models.CharField(help_text='Código único da visita', max_length=10, unique=True, verbose_name='Código da Visita'),
        ),
    ]
