# Generated by Django 5.2 on 2025-07-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0004_alter_visita_codigovisita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'permissions': (('fechar_agendamento', 'Permite fazer o fechamento de uma visita'),), 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
    ]
