# Generated by Django 5.2 on 2025-07-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0005_alter_visita_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='hora',
            field=models.TimeField(blank=True, help_text='Hora da visita', null=True, verbose_name='Hora'),
        ),
    ]
