# Generated by Django 5.2 on 2025-07-07 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_cliente_email_alter_cliente_endereco_and_more'),
        ('corretores', '0006_alter_corretor_email_alter_corretor_endereco_and_more'),
        ('imovel', '0009_alter_imovel_areaprivativa_alter_imovel_areatotal_and_more'),
        ('visita', '0006_visita_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_visitas', to='cliente.cliente', verbose_name='Cliente:'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='corretor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corretor_visitas', to='corretores.corretor', verbose_name='Corretor:'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='data',
            field=models.DateField(null=True, verbose_name='Data:'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora:'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='imovel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imovel_visitas', to='imovel.imovel', verbose_name='Imóvel:'),
        ),
    ]
