# Generated by Django 5.2 on 2025-07-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0007_alter_visita_cliente_alter_visita_corretor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora:'),
        ),
    ]