# Generated by Django 5.2 on 2025-07-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0008_alter_visita_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=10),
        ),
    ]
