# Generated by Django 5.2 on 2025-07-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0009_visita_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=10),
        ),
    ]
