# Generated by Django 5.2 on 2025-05-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='codigoProprietario',
            field=models.IntegerField(help_text='Código do proprietário', unique=True, verbose_name='Código do Proprietário'),
        ),
    ]
