# Generated by Django 5.2 on 2025-05-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proprietario',
            options={},
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='codigoProprietario',
            field=models.CharField(default='Proprietario', help_text='Código único do Proprietario', max_length=10, unique=True, verbose_name='Código do Proprietario'),
        ),
    ]
