# Generated by Django 5.2 on 2025-05-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietarios', '0002_alter_proprietario_codigoproprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='codigoProprietario',
            field=models.IntegerField(blank=True, help_text='Código do proprietário', null=True, unique=True, verbose_name='Código do Proprietário'),
        ),
    ]
