# Generated by Django 5.2 on 2025-06-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietarios', '0003_alter_proprietario_codigoproprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
