# Generated by Django 5.2 on 2025-07-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietarios', '0005_alter_proprietario_email_alter_proprietario_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='codigoProprietario',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Código do Proprietário'),
            preserve_default=False,
        ),
    ]
