# Generated by Django 5.2 on 2025-05-26 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0004_cliente_codigocliente_alter_cliente_endereco'),
        ('corretores', '0001_initial'),
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoTransacao', models.CharField(default='Transacao', help_text='Código único do Transacao', max_length=10, unique=True, verbose_name='Código do Transacao')),
                ('tipoTransacao', models.CharField(choices=[('Venda', 'Venda'), ('Aluguel', 'Aluguel')], help_text='Tipo de transação (Venda ou Aluguel)', max_length=20, verbose_name='Tipo de Transação')),
                ('dataTransacao', models.DateField(help_text='Data em que a transação foi realizada', verbose_name='Data da Transação')),
                ('statusTransacao', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], help_text='Status atual da transação', max_length=20, verbose_name='Status da Transação')),
                ('valorVenda', models.DecimalField(blank=True, decimal_places=2, help_text='Valor da venda do imóvel (se aplicável)', max_digits=10, null=True, verbose_name='Valor da Venda')),
                ('codigoCliente', models.ForeignKey(help_text='Código do Cliente relacionado à transação', on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Código do Cliente')),
                ('codigoCorretor', models.ForeignKey(help_text='Código do Corretor relacionado à transação', on_delete=django.db.models.deletion.CASCADE, to='corretores.corretor', verbose_name='Código do Corretor')),
                ('codigoImovel', models.ForeignKey(help_text='Código do Imóvel relacionado à transação', on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel', verbose_name='Código do Imóvel')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
    ]
