# Generated by Django 5.2 on 2025-05-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoTransacao', models.CharField(max_length=50, unique=True)),
                ('dataTransacao', models.DateField(help_text='Data da visita', null=True, verbose_name='Data')),
                ('valorVenda', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
