# Generated by Django 5.2 on 2025-06-11 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_cliente_email_alter_cliente_endereco_and_more'),
        ('corretores', '0003_alter_corretor_email_alter_corretor_endereco_and_more'),
        ('imovel', '0003_imovel_areaprivativa_imovel_areatotal_and_more'),
        ('transacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='codigoCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Código do Cliente'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='codigoCorretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretores.corretor', verbose_name='Código do Corretor'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='codigoImovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel', verbose_name='Código do Imóvel'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='codigoTransacao',
            field=models.CharField(default='Transação', max_length=10, unique=True, verbose_name='Código da Transação'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='dataTransacao',
            field=models.DateField(verbose_name='Data da Transação'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='statusTransacao',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], max_length=20, verbose_name='Status da Transação'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipoTransacao',
            field=models.CharField(choices=[('Venda', 'Venda'), ('Aluguel', 'Aluguel')], max_length=20, verbose_name='Tipo de Transação'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valorVenda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Venda'),
        ),
    ]
