# Generated by Django 5.2 on 2025-06-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0002_alter_transacao_codigocliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='valorComissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Comissão'),
        ),
    ]
