# Generated by Django 5.2 on 2025-07-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0003_transacao_valorcomissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='codigoTransacao',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código da Transação'),
        ),
    ]
